name: Nightly Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 10 * * *'   # runs daily at 10:00 UTC (3:30 PM IST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: sudo apt-get install -y chromium-chromedriver

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --filter "Category=smoke"

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: ./DotNetSeleniumProject/Reports/ExtentReport.html
